version: "0.0.0"

services:
  client:
    build: Ecommerce-client/
    container_name: ecommerce-client
    ports: #per essere chiamato dall'esterno
      - 4200:4200 
    networks:
      - ecommerce
  
  server:
    build: Ecommerce-products/
    container_name: ecommerce-product
    networks:
      - ecommerce
    expose: #la porta che espone all'interno della nostra network
      - "8080"
    ports: #per essere chiamato dall'esterno
      - 8080:8080

networks:
  ecommerce:
    driver: bridge