version: "0.0.1"

services:
  mongodb:
    image: mongo:7.0.0
    expose:
      - "27017"
    ports:
      - 27017:27017
    volumes:
      - ecommerce-db:/data/db
    networks:
      - ecommerce

  client:
    build: Ecommerce-client/
    container_name: ecommerce-client
    ports: #per essere chiamato dall'esterno
      - 4200:4200 
    networks:
      - ecommerce
  
  products:
    build: Ecommerce-products/
    container_name: ecommerce-product
    networks:
      - ecommerce
    expose: #la porta che espone all'interno della nostra network
      - "8080"
    ports: #per essere chiamato dall'esterno
      - 8080:8080
    depends_on:
      - mongodb

networks:
  ecommerce:
    driver: bridge

volumes:
  ecommerce-db: