version: '1'
services:
  web:
    build:
      context: .
      dockerfile: ./.dockerfile
    ports:
      - "4200:4200"
    volumes:
      - /Ecommerce-client/node_modules
      - .:/Ecommerce-client